# Description: Makefile for downloading assets
default: disney

#Source: mp4
disney:
	wget -O disney.webm https://upload.wikimedia.org/wikipedia/en/transcoded/8/83/Walt_Disney_Pictures_Logo_as_of_2022.ogv/Walt_Disney_Pictures_Logo_as_of_2022.ogv.1080p.vp9.webm