# Description: Makefile for downloading assets
default: engine porsche dungeon dragon diamond armadillo bunny dragon-mesh sphere

#Source: three-mesh-bvh
engine:
	wget -O engine.gltf https://github.com/gkjohnson/three-mesh-bvh/raw/master/example/models/internal_combustion_engine/model.gltf
porsche:
	wget -O porsche.ply https://github.com/gkjohnson/three-mesh-bvh/raw/master/example/models/point_cloud_porsche_911_1.7M_vertices/scene.ply
dungeon:
	wget -O dungeon.gltf https://github.com/gkjohnson/three-mesh-bvh/raw/master/example/models/dungeon_low_poly_game_level_challenge/scene.gltf
dragon:
	wget -O dragon.glb https://github.com/gkjohnson/three-mesh-bvh/raw/master/example/models/DragonAttenuation.glb
diamond:
	wget -O diamond.glb https://github.com/gkjohnson/three-mesh-bvh/raw/master/example/models/diamond.glb


# Source: OpenGL-Examples
armadillo:
	wget -O armadillo_lowres.obj https://github.com/cgibson/OpenGL-Examples/raw/master/models/armadillo_lowres.obj
	wget -O armadillo_midres.obj https://github.com/cgibson/OpenGL-Examples/raw/master/models/armadillo_midres.obj
bunny:
	wget -O bunny2.obj https://github.com/cgibson/OpenGL-Examples/raw/master/models/bunny2.obj
dragon-mesh:
	wget -O dragon.obj https://github.com/cgibson/OpenGL-Examples/raw/master/models/dragon.obj
sphere:
	wget -O sphere.obj https://github.com/cgibson/OpenGL-Examples/raw/master/models/sphere.obj