default:
	wget -O cubic_rgb.jpg https://upload.wikimedia.org/wikipedia/commons/0/01/Cubic_Structure.jpg
	wget -O cubic_depth.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Cubic_Frame_Stucture_and_Floor_Depth_Map.jpg/1600px-Cubic_Frame_Stucture_and_Floor_Depth_Map.jpg
